apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: contrib
  name: contrib
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contrib
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: contrib
    spec:
      containers:
      - image: thegathering/contrib:latest
        name: contrib
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 50m
        ports:
        - containerPort: 80
          protocol: TCP
